# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DATA_DIR_COVID": "00_datos.ipynb",
         "asegura_archivos_covid_disponibles": "00_datos.ipynb",
         "columnas_comunes": "00_datos.ipynb",
         "arregla_cvegeo": "00_datos.ipynb",
         "carga_datos_covid19_MX": "00_datos.ipynb",
         "agrupa_casos_municipios": "00_datos.ipynb",
         "leer_variables_municipales": "00_datos.ipynb",
         "unir_casos_estadisticas_municipales": "00_datos.ipynb",
         "tabla_covid_indicadores_municipales": "00_datos.ipynb",
         "municipios_urbanos": "00_datos.ipynb",
         "show_feature_importances": "01_vulnerabilidad.ipynb",
         "mostrar_coeficientes_PLS": "01_vulnerabilidad.ipynb",
         "agregar_conteo_pruebas": "01_vulnerabilidad.ipynb",
         "agregar_tasas_municipales": "01_vulnerabilidad.ipynb",
         "caracteristicas_modelos_municipios": "01_vulnerabilidad.ipynb",
         "ajustar_pls_letalidad": "01_vulnerabilidad.ipynb",
         "ajustar_rf_letalidad": "01_vulnerabilidad.ipynb",
         "calificar_municipios_letalidad": "01_vulnerabilidad.ipynb",
         "calificar_municipios_letalidad_formato_largo": "01_vulnerabilidad.ipynb",
         "seleccionar_caracteristicas": "01_vulnerabilidad.ipynb",
         "calcular_indices_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "calcular_indices_vulnerabilidad_formato_largo": "01_vulnerabilidad.ipynb",
         "calcular_periodo_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "agregar_periodo_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "calcular_vulnerabilidad_urbana": "01_vulnerabilidad.ipynb",
         "agregar_vulnerabilidad_entidades": "01_vulnerabilidad.ipynb",
         "guardar_resultados_csv": "01_vulnerabilidad.ipynb",
         "mapas_serie_letalidad": "01_vulnerabilidad.ipynb",
         "mapas_serie_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "guardar_shape_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "checkpoint_vulnerabilidad": "01_vulnerabilidad.ipynb",
         "cargar_checkpoint_vulnerabilidad": "01_vulnerabilidad.ipynb"}

modules = ["datos.py",
           "vulnerabilidad.py"]

doc_url = "https://rausial.github.io/covid19_vulnerabilidad_mex/"

git_url = "https://github.com/rausial/covid19_vulnerabilidad_mex/tree/master/"

def custom_doc_links(name): return None
